# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_missionCommander.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MissionCommander(object):
    def setupUi(self, MissionCommander):
        MissionCommander.setObjectName(_fromUtf8("MissionCommander"))
        MissionCommander.resize(601, 344)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(MissionCommander)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.saveMissionList = QtGui.QPushButton(MissionCommander)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveMissionList.sizePolicy().hasHeightForWidth())
        self.saveMissionList.setSizePolicy(sizePolicy)
        self.saveMissionList.setObjectName(_fromUtf8("saveMissionList"))
        self.horizontalLayout_5.addWidget(self.saveMissionList)
        self.loadMissionList = QtGui.QPushButton(MissionCommander)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadMissionList.sizePolicy().hasHeightForWidth())
        self.loadMissionList.setSizePolicy(sizePolicy)
        self.loadMissionList.setObjectName(_fromUtf8("loadMissionList"))
        self.horizontalLayout_5.addWidget(self.loadMissionList)
        self.gridLayout.addLayout(self.horizontalLayout_5, 8, 0, 1, 1)
        self.missionTypeCB = QtGui.QComboBox(MissionCommander)
        self.missionTypeCB.setObjectName(_fromUtf8("missionTypeCB"))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.missionTypeCB.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.missionTypeCB, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lookLeft = QtGui.QRadioButton(MissionCommander)
        self.lookLeft.setChecked(True)
        self.lookLeft.setObjectName(_fromUtf8("lookLeft"))
        self.horizontalLayout_4.addWidget(self.lookLeft)
        self.lookRight = QtGui.QRadioButton(MissionCommander)
        self.lookRight.setObjectName(_fromUtf8("lookRight"))
        self.horizontalLayout_4.addWidget(self.lookRight)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(MissionCommander)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.maxTimeLineEdit = QtGui.QLineEdit(MissionCommander)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxTimeLineEdit.sizePolicy().hasHeightForWidth())
        self.maxTimeLineEdit.setSizePolicy(sizePolicy)
        self.maxTimeLineEdit.setObjectName(_fromUtf8("maxTimeLineEdit"))
        self.verticalLayout.addWidget(self.maxTimeLineEdit)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox_3 = QtGui.QCheckBox(MissionCommander)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_2.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(MissionCommander)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_2.addWidget(self.checkBox_4, 2, 1, 1, 1)
        self.useLaser = QtGui.QCheckBox(MissionCommander)
        self.useLaser.setObjectName(_fromUtf8("useLaser"))
        self.gridLayout_2.addWidget(self.useLaser, 1, 1, 1, 1)
        self.useKalmanFilter = QtGui.QCheckBox(MissionCommander)
        self.useKalmanFilter.setChecked(True)
        self.useKalmanFilter.setObjectName(_fromUtf8("useKalmanFilter"))
        self.gridLayout_2.addWidget(self.useKalmanFilter, 1, 0, 1, 1)
        self.parameterStringInputs = QtGui.QPlainTextEdit(MissionCommander)
        self.parameterStringInputs.setObjectName(_fromUtf8("parameterStringInputs"))
        self.gridLayout_2.addWidget(self.parameterStringInputs, 3, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 6, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(MissionCommander)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.useGeneralWaypoint = QtGui.QLineEdit(MissionCommander)
        self.useGeneralWaypoint.setObjectName(_fromUtf8("useGeneralWaypoint"))
        self.verticalLayout_3.addWidget(self.useGeneralWaypoint)
        self.gridLayout.addLayout(self.verticalLayout_3, 4, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(MissionCommander)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.missionNameLineEdit = QtGui.QLineEdit(MissionCommander)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.missionNameLineEdit.sizePolicy().hasHeightForWidth())
        self.missionNameLineEdit.setSizePolicy(sizePolicy)
        self.missionNameLineEdit.setObjectName(_fromUtf8("missionNameLineEdit"))
        self.verticalLayout_2.addWidget(self.missionNameLineEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.addMissionButton = QtGui.QPushButton(MissionCommander)
        self.addMissionButton.setObjectName(_fromUtf8("addMissionButton"))
        self.horizontalLayout_3.addWidget(self.addMissionButton)
        self.removeMissionButton = QtGui.QPushButton(MissionCommander)
        self.removeMissionButton.setObjectName(_fromUtf8("removeMissionButton"))
        self.horizontalLayout_3.addWidget(self.removeMissionButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.missionListWidget = QtGui.QListWidget(MissionCommander)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.missionListWidget.sizePolicy().hasHeightForWidth())
        self.missionListWidget.setSizePolicy(sizePolicy)
        self.missionListWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.missionListWidget.setObjectName(_fromUtf8("missionListWidget"))
        self.verticalLayout_6.addWidget(self.missionListWidget)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.moveUp = QtGui.QPushButton(MissionCommander)
        self.moveUp.setObjectName(_fromUtf8("moveUp"))
        self.horizontalLayout_6.addWidget(self.moveUp)
        self.moveDown = QtGui.QPushButton(MissionCommander)
        self.moveDown.setObjectName(_fromUtf8("moveDown"))
        self.horizontalLayout_6.addWidget(self.moveDown)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.missionDebugCheckbox = QtGui.QCheckBox(MissionCommander)
        self.missionDebugCheckbox.setObjectName(_fromUtf8("missionDebugCheckbox"))
        self.verticalLayout_6.addWidget(self.missionDebugCheckbox)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.missionDebugWidget = QtGui.QWidget(MissionCommander)
        self.missionDebugWidget.setEnabled(True)
        self.missionDebugWidget.setObjectName(_fromUtf8("missionDebugWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.missionDebugWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.debugTestingLayout = QtGui.QVBoxLayout()
        self.debugTestingLayout.setObjectName(_fromUtf8("debugTestingLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.nextMissionButton = QtGui.QPushButton(self.missionDebugWidget)
        self.nextMissionButton.setObjectName(_fromUtf8("nextMissionButton"))
        self.gridLayout_3.addWidget(self.nextMissionButton, 0, 1, 1, 1)
        self.previousMissionButton = QtGui.QPushButton(self.missionDebugWidget)
        self.previousMissionButton.setObjectName(_fromUtf8("previousMissionButton"))
        self.gridLayout_3.addWidget(self.previousMissionButton, 0, 0, 1, 1)
        self.nextFlagButton = QtGui.QPushButton(self.missionDebugWidget)
        self.nextFlagButton.setObjectName(_fromUtf8("nextFlagButton"))
        self.gridLayout_3.addWidget(self.nextFlagButton, 1, 1, 1, 1)
        self.previousFlagButton = QtGui.QPushButton(self.missionDebugWidget)
        self.previousFlagButton.setObjectName(_fromUtf8("previousFlagButton"))
        self.gridLayout_3.addWidget(self.previousFlagButton, 1, 0, 1, 1)
        self.debugTestingLayout.addLayout(self.gridLayout_3)
        self.missionDebugOutput = QtGui.QPlainTextEdit(self.missionDebugWidget)
        self.missionDebugOutput.setObjectName(_fromUtf8("missionDebugOutput"))
        self.debugTestingLayout.addWidget(self.missionDebugOutput)
        self.verticalLayout_4.addLayout(self.debugTestingLayout)
        self.horizontalLayout_2.addWidget(self.missionDebugWidget)

        self.retranslateUi(MissionCommander)
        QtCore.QObject.connect(self.missionDebugCheckbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.missionDebugWidget.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MissionCommander)

    def retranslateUi(self, MissionCommander):
        MissionCommander.setWindowTitle(_translate("MissionCommander", "Mission Commander", None))
        self.saveMissionList.setText(_translate("MissionCommander", "Save Missions", None))
        self.loadMissionList.setText(_translate("MissionCommander", "Load Missions", None))
        self.missionTypeCB.setItemText(0, _translate("MissionCommander", "Select a Mission Type", None))
        self.missionTypeCB.setItemText(1, _translate("MissionCommander", "Navigation", None))
        self.missionTypeCB.setItemText(2, _translate("MissionCommander", "Qualification Gate", None))
        self.missionTypeCB.setItemText(3, _translate("MissionCommander", "Buoys - Red", None))
        self.missionTypeCB.setItemText(4, _translate("MissionCommander", "Buoys - Green", None))
        self.missionTypeCB.setItemText(5, _translate("MissionCommander", "Buoys - Yellow", None))
        self.missionTypeCB.setItemText(6, _translate("MissionCommander", "Football Gate", None))
        self.missionTypeCB.setItemText(7, _translate("MissionCommander", "Torpedo Board - Locate", None))
        self.missionTypeCB.setItemText(8, _translate("MissionCommander", "Torpedo Board - Grab Handle", None))
        self.missionTypeCB.setItemText(9, _translate("MissionCommander", "Torpedo Board - Fire Torpedos", None))
        self.missionTypeCB.setItemText(10, _translate("MissionCommander", "Dropper - Locate", None))
        self.missionTypeCB.setItemText(11, _translate("MissionCommander", "Dropper - Grab Handle", None))
        self.missionTypeCB.setItemText(12, _translate("MissionCommander", "Dropper - Drop", None))
        self.missionTypeCB.setItemText(13, _translate("MissionCommander", "Octogon", None))
        self.lookLeft.setText(_translate("MissionCommander", "Look to the Left", None))
        self.lookRight.setText(_translate("MissionCommander", "Look to the Right", None))
        self.label.setText(_translate("MissionCommander", "Max Time in Seconds", None))
        self.checkBox_3.setText(_translate("MissionCommander", "Second Option", None))
        self.checkBox_4.setText(_translate("MissionCommander", "One More Option", None))
        self.useLaser.setText(_translate("MissionCommander", "Use Laser", None))
        self.useKalmanFilter.setText(_translate("MissionCommander", "Use Kalman Filter", None))
        self.label_3.setText(_translate("MissionCommander", "Use General Waypoint from Mission", None))
        self.label_2.setText(_translate("MissionCommander", "Mission Name", None))
        self.addMissionButton.setText(_translate("MissionCommander", "Add Mission", None))
        self.removeMissionButton.setText(_translate("MissionCommander", "Remove Mission", None))
        self.moveUp.setText(_translate("MissionCommander", "Up", None))
        self.moveDown.setText(_translate("MissionCommander", "Down", None))
        self.missionDebugCheckbox.setText(_translate("MissionCommander", "Mission Debug", None))
        self.nextMissionButton.setText(_translate("MissionCommander", "Next Mission", None))
        self.previousMissionButton.setText(_translate("MissionCommander", "Previous Mission", None))
        self.nextFlagButton.setText(_translate("MissionCommander", "Next Flag", None))
        self.previousFlagButton.setText(_translate("MissionCommander", "Previous Flag", None))

